---
name: "Build"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-dotnet:
    uses: timmo001/workflows/.github/workflows/build-msbuild-windows.yml@master
    with:
      code-path: WindowsSensors
      output-name: windowssensors-build
      output-path: windowssensors/WindowsSensors/bin
      package: SystemBridgeWindowsSensors.sln
  build:
    needs:
      - build-dotnet
    uses: timmo001/workflows/.github/workflows/build-python-windows.yml@master
    with:
      additional-artifacts-name: windowssensors-build
      additional-artifacts-path: windowssensors/WindowsSensors/bin
