---
name: Publish

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - "CI"
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    name: 👷 Publish to ${{ matrix.target.name }}
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: NPM
            registry: https://registry.npmjs.org
            token: ${{ secrets.NPM_TOKEN }}
          - name: GitHub
            registry: https://npm.pkg.github.com
            token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
        with:
          clean: ${{ matrix.os.server != 'self-hosted' }}
          ref: ${{ github.head_ref }}
      - name: 🏗 Set up Node.js
        if: matrix.os.server != 'self-hosted'
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
          cache: yarn
          registry-url: ${{ matrix.target.registry }}
          scope: "@system-bridge"
      - name: 🏗 Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: 🏗 Run build
        run: |
          yarn build
      - name: ↗ Publish
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ matrix.target.token }}
